<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>42fe4582-44c6-414d-9cf8-04db262e3c76</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="images\**" />
    <Content Remove="images\**" />
    <EmbeddedResource Remove="images\**" />
    <None Remove="images\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="logs\" />
  </ItemGroup>

  <ItemGroup>
	  <InternalsVisibleTo Include="KronoGeo_Api.TestUnitaire" />	
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KronoGeo_Api.Infrastructure\KronoGeo_Api.Infrastructure.csproj" />
    <ProjectReference Include="..\KronoGeo_Api.Models\KronoGeo_Api.Models.csproj" />
  </ItemGroup>

</Project>
